### ISSUE TITLE
yocto misspelled as yotco?

### ISSUE THREAD

**Issue by AnttiLukats** [systemviewinc/fpga_driver#1]
it seems the path name should include "yocto" and not "yotco"...

vsi_driver_build_yotco
should be: vsi_driver_build_yocto ?

**Comment by udnaan** [comment]
@AnttiLukats This does seems to be a typo.

@MenezesM Can you look into this?

**Comment by MenezesM** [comment]
Thanks @AnttiLukats for the heads up, I've fixed it in the development branch, and that should be the master very soon.
